#!/usr/bin/python3
# -*- coding: utf-8 -*-
# SPDX-License-Identifier: MIT
# (c) 2024 TU Ilmenau, FG EMS, Carsten Andrich <carsten.andrich@tu-ilmenau.de>

import asyncio
import calendar
import enum
import io
import json
import logging
import math
import os
import signal
import socket
import time
from typing import Self

import asyncio_mqtt

_logger = logging.getLogger(__name__)

# FS740 configuration options
# pdftotext -f 113 -l 160 FS740m.pdf - | grep -E "(GPS|ROUT|SOUR|TBAS|SYST).+\\?" FS740m.txt | uniq
_FS740_CFG_SCPI = [
    "*IDN?",
    "*OPT?",
    "GPS:CONFig:CONStellation?",
    "GPS:CONFig:MODe?",
    "GPS:CONFig:SURVey:MODe?",
    "GPS:CONFig:SURVey:FIXes?",
    "GPS:CONFig:TIMing:ALIGnment?",
    "GPS:CONFig:TIMing:QUALity?",
    "GPS:CONFig:TIMing:ADELay?",
    "ROUTe:OPTion1?",
    "ROUTe:OPTion2?",
    "ROUTe:OPTion3?",
    "SOURce1:FREQuency?",
    "SOURce2:FREQuency?",
    "SOURce3:FREQuency?",
    "SOURce2:FUNCtion:SHAPe?",
    "SOURce3:FUNCtion:SHAPe?",
    "SOURce1:PHASe:ADJust?",
    "SOURce2:PHASe:ADJust?",
    "SOURce3:PHASe:ADJust?",
    "SOURce1:PHASe:SYNChronize:AUTo?",
    "SOURce2:PHASe:SYNChronize:AUTo?",
    "SOURce3:PHASe:SYNChronize:AUTo?",
    "SOURce1:PHASe:SYNChronize:TDELay?",
    "SOURce2:PHASe:SYNChronize:TDELay?",
    "SOURce3:PHASe:SYNChronize:TDELay?",
    "SOURce3:PULSe:DCYCle?",
    "SOURce3:PULSe:PERiod?",
    "SOURce3:PULSe:VIEW?",
    "SOURce3:PULSe:WIDTh?",
    "SOURce1:VOLTage:LEVel?",
    "SOURce2:VOLTage:LEVel?",
    "SOURce1:VOLTage:UNITs?",
    "SOURce2:VOLTage:UNITs?",
    "TBASe:CONFig:BWIDth?",
    "TBASe:CONFig:HMODe?",
    "TBASe:CONFig:LOCK?",
    "TBASe:CONFig:TINTerval:LIMit?"
]


class TimebaseState(enum.Enum):
    # https://www.thinksrs.com/downloads/pdfs/manuals/FS740m.pdf#page=158

    # Instrument has been recently powered up
    POWERUP = "POW"

    # GPS receiver is searching for satellites
    SEARCH = "SEAR"

    # Waiting for frequency of the timebase to stabilize
    STABILIZE = "STAB"

    # Validating time of day reported by GPS
    VTIME = "VTIM"

    # Locked to GPS
    LOCKED = "LOCK"

    # Manual: in holdover at the request of the user
    MANUAL = "MAN"

    # No GPS: in holdover because timing pulses are not
    # being generated by the GPS receiver.
    NO_GPS = "NGPS"

    # Bad GPS: in holdover because timing error of the
    # timebase relative to GPS exceeds the limit specified
    # in the command TBAS:CONF:LIM.
    BAD_GPS = "BGPS"

    # Installed Rb oscillator is unlocked
    RB_UNLOCKED = "UNL"

    # invalid state not documented by the manual
    INVALID = None


class StatusQuestionable(enum.Enum):
    # https://www.thinksrs.com/downloads/pdfs/manuals/FS740m.pdf#page=85

    # Instrument time of day has not been set by the GPS
    # receiver. Absolute time measurements are invalid.
    TIME_OF_DAY = 2**0

    # The timebase is still warming up. Frequency drift will be
    # much larger than normal.
    WARMUP = 2**1

    # The timebase is not locked to GPS. Time and frequency
    # measurements may be degraded.
    TIME_UNLOCK = 2**2

    # The timebase has not been locked to GPS long enough to
    # reach optimum frequency stability.
    FREQ_STABILITY = 2**5

    # The installed Rb timebase is unlocked. Its frequency is not stable.
    RB_UNLOCK = 2**10

    # One of the internal Pll circuits in the FS740 has come
    # unlocked. This may signal a need for instrument repair.
    PLL_UNLOCK = 2**11

    # Indicates that the frequency control of the internal TCXO is
    # near the rail.
    EFC_10MHZ = 2**12

    # Indicates that the frequency control for the installed
    # timebase is saturated. This might indicate a large timing
    # error.
    EFC_GPS = 2**13

    # unknown bits
    UNKNOWN3  = 2**3
    UNKNOWN4  = 2**4
    UNKNOWN6  = 2**6
    UNKNOWN7  = 2**7
    UNKNOWN8  = 2**8
    UNKNOWN9  = 2**9
    UNKNOWN14 = 2**14
    UNKNOWN15 = 2**15


class StatusGPS(enum.Enum):
    # https://www.thinksrs.com/downloads/pdfs/manuals/FS740m.pdf#page=87

    # Time of day information has not been received from
    # the satellites, yet.
    TIME_NOT_SET = 2**0

    # The GPS antenna does not appear to be connected to
    # the receiver input.
    ANTENNA_OPEN = 2**1

    # The receiver input appears to be shorted.
    ANTENNAS_SHORT = 2**2

    # No GPS satellites have been found.
    NO_SATELLITES = 2**3

    # The UTC offset from GPS is unknown. The offset is
    # recorded in the almanac which can take up to 15
    # minutes to download from the satellites.
    UTC_UNKNOWN = 2**4

    # A position survey is in progress.
    SURVEY_IN_PROGRESS = 2**5

    # No surveyed position has been stored in nonvolatile memory.
    NO_POS_STORED = 2**6

    # A leap second is pending. When pending, they are
    # normally scheduled for the end of the day on June 30th
    # or December 31st.
    LEAP_SEC_PENDING = 2**7

    # The stored position does not appear to be correct
    # according to data now being collected. A new survey
    # may need to be collected.
    POS_QUESTIONABLE = 2**9

    # A complete almanac has not been downloaded from
    # the GPS satellites, yet. It can take up to 15 minutes of
    # continuous tracking of satellites to download the
    # almanac.
    ALMANAC_INCOMPLETE = 2**11

    # Timing pulses are not being generated by the receiver.
    # Timing pulses must be generated in order for the
    # FS740 to lock its timebase to GPS.
    NO_TIMING_PULSES = 2**12

    # unknown bits
    UNKNOWN8  = 2**8
    UNKNOWN10 = 2**10
    UNKNOWN13 = 2**13
    UNKNOWN14 = 2**14
    UNKNOWN15 = 2**15


class AsyncFS740:
    def __init__(self, addr: str, port: int = 5025, timeout: float = 1.):
        self._addr = addr
        self._port = port
        self._timeout = timeout

    async def __aenter__(self) -> Self:
        async with asyncio.timeout(self._timeout):
            self._reader, self._writer = await asyncio.open_connection(self._addr, self._port)

        # verify peer is an FS740
        idn = await self.ask("*IDN?")
        if not idn.startswith("Stanford Research Systems,FS740,"):
            raise RuntimeError(f"device is not an SRS FS740: {idn}")

        return self

    async def __aexit__(self, exc_type, exc_value, traceback):
        self._writer.close()
        await self._writer.wait_closed()

    async def ask(self, query: str) -> str:
        async with asyncio.timeout(self._timeout):
            self._writer.write(f"{query}\r\n".encode("ascii"))
            await self._writer.drain()
            resp = await self._reader.readuntil(b"\r\n")
            if len(resp) == 0:
                raise EOFError
            return resp.removesuffix(b"\r\n").decode("ascii")

    async def ask_bool(self, query: str) -> bool:
        return bool(int(await self.ask(query)))

    async def ask_float(self, query: str) -> float:
        return float(await self.ask(query))

    async def ask_int(self, query: str) -> int:
        return int(await self.ask(query))

    async def write(self, query: str):
        async with asyncio.timeout(self._timeout):
            self._writer.write(f"{query}\r\n".encode("ascii"))
            await self._writer.drain()

    async def set(self, command: str, value: bool | float | int | str):
        if isinstance(value, bool):
            value = int(value)

        await self.write(f"{command} {value!s}")
        await self.write("*WAI")
        resp = await self.ask(f"{command}?")

        if resp != str(value):
            raise ValueError("setting value failed: {command} {value!s} -> {resp!s}")

    async def get_config(self) -> dict:
        cfg = {}
        for cmd in _FS740_CFG_SCPI:
            value = await self.ask(cmd)
            try:
                cfg[cmd] = int(value)
            except ValueError:
                try:
                    cfg[cmd] = float(value)
                except ValueError:
                    cfg[cmd] = value

        return cfg

    async def get_state(self) -> TimebaseState:
        try:
            return TimebaseState(await self.ask("TBAS:STAT?"))
        except ValueError:
            return TimebaseState.INVALID

    async def get_syst_err(self) -> (int, str):
        syst_err = await self.ask("SYST:ERR?")
        errno, errmsg = syst_err.split(",", 1)
        return int(errno), errmsg.lstrip('"').rstrip('"')

    async def get_gps_pos(self) -> (float, float, float):
        # https://www.thinksrs.com/downloads/pdfs/manuals/FS740m.pdf#page=129
        gps_pos = await self.ask("GPS:POS?")
        lat_rad, lon_rad, height_msl = (float(f) for f in gps_pos.split(","))
        # convert from radians to degrees
        lat_deg = round(lat_rad * 180. / math.pi, 7)
        lon_deg = round(lon_rad * 180. / math.pi, 7)
        return lat_deg, lon_deg, height_msl

    async def get_time_ns(self) -> int:
        # https://www.thinksrs.com/downloads/pdfs/manuals/FS740m.pdf#page=151
        date = await self.ask("SYST:DATE?")
        date = date.split(",")
        year, month, day = int(date[0]), int(date[1]), int(date[2])
        # https://www.thinksrs.com/downloads/pdfs/manuals/FS740m.pdf#page=153
        time = await self.ask("SYST:TIME?")
        time = time.split(",")
        hour, minute, sec = int(time[0]), int(time[1]), float(time[2])

        # convert to POSIX time in integer nanoseconds
        posix_sec = calendar.timegm((year, month, day, hour, minute, int(sec)))
        posix_ns  = posix_sec * 1_000_000_000 \
                  + round((sec - int(sec)) * 1e9)
        return posix_ns

    async def get_tbas_tint(self) -> float | None:
        # https://www.thinksrs.com/downloads/pdfs/manuals/FS740m.pdf#page=159
        # FS740 w/ firmware ver4.25.11 does not respond to TBAS:TINT? between
        # power up and the first GNSS fix, so use shorter timeout and simply
        # return None in that case.
        try:
            async with asyncio.timeout(0.1):
                return float(await self.ask("TBAS:TINT?"))
        except asyncio.TimeoutError:
            return None

    async def get_num_acquired_sats(self) -> int:
        # the "number of satellites being tracked" in GPS:SAT:TRAC is *NOT* the
        # number of satellites from which a signal is being received.
        # GPS:SAT:TRAC will report tracked satellites after loss of GNSS signal.
        # to get the number of satellites acquired by the FS740 GNSS receiver,
        # count "acquired" fields in GPS:SAT:TRAC:STAT.
        # https://www.thinksrs.com/downloads/pdfs/manuals/FS740m.pdf#page=131
        gps_sat_trac_stat = await self.ask("GPS:SAT:TRAC:STAT?")
        num_acquired_sats = 0
        for acquired in gps_sat_trac_stat.split(",")[1::8]:
            if acquired == "1":
                num_acquired_sats += 1
            elif acquired == "0":
                continue
            else:
                raise ValueError(f"invalid GPS:SAT:TRAC:STAT value: {gps_sat_trac_stat}")
        return num_acquired_sats

    async def get_status_gps(self) -> set:
        bits = set()
        stat_gps = int(await self.ask("STAT:GPS?"))
        for bit in StatusGPS:
            if stat_gps & bit.value:
                bits.add(bit)
        return bits

    async def get_status_questionable(self) -> set:
        bits = set()
        stat_ques = int(await self.ask("STAT:QUES?"))
        for bit in StatusQuestionable:
            if stat_ques & bit.value:
                bits.add(bit)
        return bits


class AsyncMqttClient(asyncio_mqtt.AsyncMqttClientLog):
    def on_reconnect_error(self, reason_code, exception):
        # suppress logging of reconnect errors
        pass


class LogFS740(AsyncFS740):
    def __init__(self, addr: str, port: int = 5025, timeout: float = 1., stationary: bool = False):
        super().__init__(addr, port, timeout)
        self._stationary = stationary

        self._hostname = socket.gethostname()

    async def __aenter__(self) -> Self:
        await super().__aenter__()
        self._log_file = open(f"fs740_{self._hostname}_{self._addr}_{int(time.time())}.log", "xt")
        self._log_file.__enter__()

    async def __aexit__(self, exc_type, exc_value, traceback):
        self._log_file.__exit__(exc_type, exc_value, traceback)
        await super().__aexit__(exc_type, exc_value, traceback)

    async def log(self, mqtt_client: AsyncMqttClient, mqtt_topic: str):
        error: str | None = None

        # the 10 MHz output (SOURce1) may be used as a reference singal by
        # external devices immediately after power up. the 10 MHz signal phase
        # must remain stable to avoid upsetting the (PLLs of) external devices.
        # disable auto synchronization to prevent phase jumps. according to the
        # documentation, auto sync jumps the phase when changing the signal
        # frequency, disabling the respective output for up to 1 second.
        # however activating auto sync is also required to get the PPS signal
        # (SOURce3) aligned to integer seconds when the FS740 locks to GNSS for
        # the first time since power up, which is not documented by the manual:
        # https://www.thinksrs.com/downloads/pdfs/manuals/FS740m.pdf#page=138
        # disable auto sync for the 10 MHz (SOURce1) and AUX signals (SOURce2)
        await self.set("SOUR1:PHASE:SYNC:AUTO", False)
        await self.set("SOUR2:PHASE:SYNC:AUTO", False)
        # enable auto sync for the 1 PPS signal (SOURce3)
        await self.set("SOUR3:PHASE:SYNC:AUTO", True)

        # return from holdover mode to GNSS lock by slewing the timebase instead
        # of jumping it. although not expressly documented, the 10 MHz signal
        # phase would presumably also jump, which is undesirable (see above).
        # https://www.thinksrs.com/downloads/pdfs/manuals/FS740m.pdf#page=56
        # https://www.thinksrs.com/downloads/pdfs/manuals/FS740m.pdf#page=155
        await self.set("TBAS:CONF:HMOD", "SLEW")

        # dump FS740 configuration
        print(json.dumps(await self.get_config()), file=self._log_file)

        # start surveying if so configured and survey is required
        if self._stationary:
            if  not await self.ask_bool("GPS:POS:HOLD:STAT?") \
            and not await self.ask_bool("GPS:POS:SURV:STAT?"):
                await self.write("GPS:POS:SURV:STAR")
        # when configured for non-stationary use in mobile scenarios, verify
        # that the FS740 is not already configured for automatic survey (see
        # GPS:CONF:SURV:MODE), not already in position hold from a previously
        # completed survey (see GPS:POS:HOLD:STAT), and not currently surveying
        # (see GPS:POS:SURV:STAT).
        # unfortunately, all cases require a power cycle, because no SCPI to
        # undo position hold mode exists.
        # https://www.thinksrs.com/downloads/pdfs/manuals/FS740m.pdf#page=127
        # https://www.thinksrs.com/downloads/pdfs/manuals/FS740m.pdf#page=129
        # https://www.thinksrs.com/downloads/pdfs/manuals/FS740m.pdf#page=130
        else:
            # if FS740 is configured for automatic surveying or loading of a
            # previous survey from non-volatile memory, update configuration.
            if (await self.ask("GPS:CONF:SURV:MODE?")) != "DIS":
                await self.set("GPS:CONF:SURV:MODE", "DIS")
                await self.write("GPS:CONF:SAVE")
                error = "Power-cycle FS740 to disable stationary mode!"

            # also need a restart if a survey has already completed or is
            # currently in progress
            if await self.ask_bool("GPS:POS:HOLD:STAT?") \
            or await self.ask_bool("GPS:POS:SURV:STAT?"):
                error = "Power-cycle FS740 to disable stationary mode!"

            if error is not None:
                _logger.error(error)

        pps_synced = False
        while True:
            # align to next full second
            now = time.time()
            await asyncio.sleep(1 + int(now) - now)

            # explicitly synchronize the PPS signal (SOURce3) edge to UTC
            # seconds when FS740 locks for the first time.
            # FIXME: will sync irregardless of in STAT:GPS or STAT:QUES
            state = await self.get_state()
            if not pps_synced and state is TimebaseState.LOCKED:
                await self.write("SOUR3:PHAS:SYNC")
                pps_synced = True

            # query data written to log file (use SCPI command names as keys)
            data_file = {
                "time_ns": None,
                "TBAS:STAT": state.name,
                "num_sats_acquired": await self.get_num_acquired_sats(),
                "GPS:POS": await self.get_gps_pos(),
                "GPS:POS:HOLD:STAT": await self.ask_bool("GPS:POS:HOLD:STAT?"),
                "GPS:POS:SURV:PROG": await self.ask_int("GPS:POS:SURV:PROG?"),
                "TBAS:FCON": await self.ask_float("TBAS:FCON?"),
                "TBAS:TCON": await self.ask_int("TBAS:TCON?"),
                "TBAS:TINT": await self.get_tbas_tint(),
                "TBAS:LOCK": await self.ask_int("TBAS:LOCK?"),
                "TBAS:HOLD": await self.ask_int("TBAS:HOLD?"),
            }

            # prepare data published via MQTT (translate SCPI command names)
            data_mqtt = {
                "time_ns": None,
                "lock": state.name,
                "num_sats": data_file["num_sats_acquired"],
                "offset_ns": round(data_file["TBAS:TINT"] * 1e9, 3) if data_file["TBAS:TINT"] is not None else None,
                "time_const": data_file["TBAS:TCON"],
                "stationary": data_file["GPS:POS:HOLD:STAT"]
            }

            stat_gps = await self.get_status_gps()
            if len(stat_gps) > 0:
                data_file["STAT:GPS"] = [bit.name for bit in stat_gps]

            stat_ques = await self.get_status_questionable()
            if len(stat_ques) > 0:
                data_file["STAT:QUES"] = [bit.name for bit in stat_ques]

            # for MQTT, combine STAT:GPS and STAT:QUES into single list
            warnings = stat_gps.copy()
            warnings.update(stat_ques)
            # remove insignificant StatusGPS.NO_POS_STORED
            if StatusGPS.NO_POS_STORED in warnings:
                warnings.remove(StatusGPS.NO_POS_STORED)
            if len(warnings) > 0:
                data_mqtt["warning"] = sorted([bit.name for bit in warnings])

            errno, errmsg = await self.get_syst_err()
            if error is not None:
                data_file["SYST:ERR"] = [None, error]
                data_mqtt["error"] = error
            elif errno != 0:
                data_file["SYST:ERR"] = [errno, errmsg]
                data_mqtt["error"] = f"{errno},{errmsg}"

            # query recent timestamp unaffected by RTTs of previous queries
            time_ns = await self.get_time_ns()
            data_file["time_ns"] = time_ns
            data_mqtt["time_ns"] = time_ns

            # publish and log data, ignoring any MQTT errors
            mqtt_client.publish(mqtt_topic, json.dumps(data_mqtt))
            print(json.dumps(data_file), file=self._log_file)


async def main(addr: str, stationary: bool, timeout: float):
    # setup graceful termination by cancelling task on SIGINT/SIGTERM
    if os.name == "posix":
        loop = asyncio.get_running_loop()
        task = asyncio.current_task()
        loop.add_signal_handler(signal.SIGINT,  lambda: task.cancel())
        loop.add_signal_handler(signal.SIGTERM, lambda: task.cancel())

    # configure MQTT client
    mqtt_client = AsyncMqttClient("192.0.2.1", async_connect=True,
                                  connect_delay=[0., 1., 2., 3., 5.],
                                  keepalive=5)
    mqtt_topic = f"usrp_rxtx/gnssdo/fs740/{socket.gethostname()}/{addr}"

    # configure FS740 client
    fs740 = LogFS740(addr, timeout=timeout, stationary=args.stationary)

    while True:
        # (re-)connect to FS740 indefinitely on expected errors
        try:
            async with fs740, mqtt_client:
                await fs740.log(mqtt_client, mqtt_topic)
        # timed out while connecting or waiting for query response
        except asyncio.TimeoutError:
            _logger.error("FS740 connection or response timed out")
        # other network errors, e.g., OSError(errno.ECONNREFUSED),
        # OSError(errno.ENETDOWN), OSError(errno.ENETUNREACH),
        # OSError(errno.EHOSTUNREACH
        except OSError:
            _logger.error("FS740 network error")
        # malformed response from FS740
        except ValueError:
            _logger.exception("FS740 sent malformed response")
        # FS740 closed socket unexpectedly
        except EOFError:
            _logger.exception("FS740 closed connection unexpectedly")

        # try to reconnect soon
        await asyncio.sleep(10)


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--stationary", action="store_true",
        help="Run FS740 in stationary mode (will automatically survey position if necessary). "
             "Otherwise run in non-stationary mode suitable for mobile use. "
             "Disabling stationary mode requires a power-cycle.")
    parser.add_argument("--timeout", type=float, default=1.0,
                    help="Timeout for connecting and queries in seconds.")
    parser.add_argument("addr", type=str,
                        help="FS740 IP address or hostname")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO)

    try:
        asyncio.run(main(args.addr, args.stationary, args.timeout))
    except (asyncio.CancelledError, KeyboardInterrupt):
        pass
